import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import Slideshow from '../components/Slideshow'
import About from '../components/About'
import Activities from '../components/Activities'
import Venue from '../components/Venue'
import Timeline from '../components/Timeline'
import Attractions from '../components/Attractions'
import Requirements from '../components/Requirements'
import Contact from '../components/Contact'
import Event from '../components/Event'

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Summer Course</title>
          <meta name="description" content='Generated by me' />
          <link rel='icon' href="/favicon.ico" />
        </Head>
        <Navbar />
        <Slideshow />
        <Main />
        <About />
        <Venue />
        <Timeline />
        <Event />
        <Activities />
        <Attractions />
        <Requirements />
        <Contact />
      </div>
    </>
  )
}
